from django.utils.translation import gettext as _
from collections import OrderedDict

DEFAULT_AFFILIATION = {("studente") : ["student", "member"]}

idem_affiliation_map = {
_("assistente universitario") : ["staff", "member"],
_("associato (ad es. CNR)"): ["member"],
_("cessato"): [],
_("collaboratore coordinato continuativo") : ["staff", "member"],
_("collaboratore linguistico") : ["staff", "member"],
_("consorziato (membro del consorzio a cui l'ente appartiene)") : ["member"],
_("convenzionato (cliente delle convenzioni)") : ["affiliate"],
_("cultore della materia") : ["staff", "member"],
_("dipendente") : ["staff", "member"],
_("dipendente altra università") : ["member"],
_("dipendente altro ente di ricerca") : ["member"],
_("dipendente azienda ospedaliera/policlinico") : ["member"],
_("dipendente di altra azienda sanitaria") : ["member"],
_("direttore amministrativo") : ["staff", "member"],
_("dirigente") : ["staff", "member"],
_("dirigente a contratto") : ["staff", "member"],
_("dirigente di ricerca") : ["staff", "member"],
_("dirigente tecnologo") : ["staff", "member"],
_("docente a contratto") : ["staff", "member"],
_("dottorando") : ["staff", "member", "student"],
_("dottorando di altra università (consorziata)") : ["member"],
_("esperto linguistico") : ["staff", "member"],
_("fornitore (dipendente o titolare delle ditte fornitrici)") : ["affiliate"],
_("interinale") : ["staff", "member"],
_("ispettore generale") : ["affiliate"],
_("laureato frequentatore/collaboratore di ricerca (a titolo gratuito)") : ["member"],
_("lavoratore occasionale (con contratto personale senza partita iva)") : ["staff", "member"],
_("lettore di scambio") : ["member"],
_("libero professionista (con contratto personale con partita iva)") : ["staff", "member"],
_("ospite / visitatore") : ["affiliate"],
_("personale tecnico-amministrativo a tempo determinato") : ["staff", "member"],
_("personale tecnico-amministrativo") : ["staff", "member"],
_("primo ricercatore") : ["staff", "member"],
_("primo tecnologo") : ["staff", "member"],
_("professore associato") : ["staff", "member"],
_("professore emerito") : ["member"],
_("professore incaricato interno") : ["staff", "member"],
_("professore incaricato esterno") : ["staff", "member"],
_("professore ordinario") : ["staff", "member"],
_("ricercatore") : ["staff", "member"],
_("specializzando") : ["staff", "member", "student"],
_("studente") : ["student", "member"],
_("studente erasmus in ingresso") : ["student"],
_("studente fuori sede (tesista, tirocinante, ...)") : ["student", "member"],
_("studente laurea specialistica") : ["student", "member"],
_("studente master") : ["student", "member"],
_("studente siss") : ["student", "member"],
_("supervisore siss") : ["staff", "member"],
_("supplente docente") : ["staff", "member"],
_("titolare di assegno di ricerca") : ["staff", "member"],
_("titolare di borsa di studio") : ["member"],
_("tecnologo") : ["staff", "member"],
_("tutor") : ["staff", "member"],
_("volontario servizio civile nazionale") : ["member"],
}


IDEM_AFFILIATION_MAP = OrderedDict(DEFAULT_AFFILIATION)
IDEM_AFFILIATION_MAP.update(OrderedDict(sorted(idem_affiliation_map.items(), key=lambda t: t[0])))
