# Generated by Django 2.0.7 on 2018-10-29 15:31

from django.db import migrations
import ldap_peoples.model_fields
import ldapdb.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapAcademiaUser',
            fields=[
                # ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('uid', ldapdb.models.fields.CharField(db_column='uid', help_text='uid', max_length=200, primary_key=True, serialize=False, verbose_name='User ID')),
                ('cn', ldapdb.models.fields.CharField(db_column='cn', help_text='cn', max_length=200, verbose_name='Name')),
                ('givenName', ldapdb.models.fields.CharField(blank=True, db_column='givenName', help_text='givenName', max_length=200, null=True, verbose_name='First Name')),
                ('sn', ldapdb.models.fields.CharField(db_column='sn', help_text='sn', max_length=200, verbose_name='Final name')),
                ('displayName', ldapdb.models.fields.CharField(blank=True, db_column='displayName', help_text='displayName', max_length=200, null=True)),
                ('telephone', ldap_peoples.model_fields.ListField(blank=True, db_column='telephoneNumber')),
                ('mail', ldap_peoples.model_fields.EmailListField(blank=True, db_column='mail', default='', null=True)),
                ('userPassword', ldapdb.models.fields.CharField(blank=True, db_column='userPassword', max_length=200, null=True, verbose_name='LDAP Password')),
                ('sambaNTPassword', ldapdb.models.fields.CharField(blank=True, db_column='sambaNTPassword', help_text='SAMBA NT Password (freeRadius PEAP)', max_length=200, null=True)),
                ('eduPersonPrincipalName', ldapdb.models.fields.CharField(blank=True, db_column='eduPersonPrincipalName', help_text='A scoped identifier for a person', max_length=200, null=True, verbose_name='Eduperson PrincipalName')),
                ('eduPersonAffiliation', ldap_peoples.model_fields.ListField(blank=True, db_column='eduPersonAffiliation', default='', help_text='Organizzazione di appartenenza dell’utente e al suo tipo di affiliazione', null=True, verbose_name='Eduperson Affiliation')),
                ('eduPersonScopedAffiliation', ldap_peoples.model_fields.ListField(blank=True, db_column='eduPersonScopedAffiliation', default='', help_text='Organizzazione di appartenenza dell’utente e al suo tipo di affiliazione scoped.Es: username@istitution', null=True, verbose_name='ScopedAffiliation')),
                ('eduPersonEntitlement', ldap_peoples.model_fields.ListField(blank=True, db_column='eduPersonEntitlement', default=['urn:mace:terena.org:tcs:personal-user', 'urn:mace:terena.org:tcs:escience-user'], help_text='eduPersonEntitlement', null=True, verbose_name='eduPersonEntitlement')),
                ('eduPersonOrcid', ldapdb.models.fields.CharField(blank=True, db_column='eduPersonOrcid', help_text='ORCID user identifier released and managed by orcid.org', max_length=200, null=True, verbose_name='EduPerson Orcid')),
                ('schacHomeOrganization', ldapdb.models.fields.CharField(blank=True, db_column='schacHomeOrganization', default='', help_text='The persons home organization using the domain of the organization.', max_length=200, null=True, verbose_name='schacHomeOrganization')),
                ('schacHomeOrganizationType', ldap_peoples.model_fields.ListField(blank=True, db_column='schacHomeOrganizationType', default='', help_text='Type of a Home Organization', null=True)),
                ('schacPersonalUniqueID', ldap_peoples.model_fields.SchacPersonalUniqueIdListField(blank=True, db_column='schacPersonalUniqueID', help_text='Unique Legal Identifier of a person, es: codice fiscale', null=True, verbose_name='schacPersonalUniqueID')),
                ('schacDateOfBirth', ldapdb.models.fields.DateField(blank=True, db_column='schacDateOfBirth', help_text='OID 1.3.6.1.4.1.1466.115.121.1.36', null=True, verbose_name='schacDateOfBirth')),
                ('schacPlaceOfBirth', ldapdb.models.fields.CharField(blank=True, db_column='schacPlaceOfBirth', default='', help_text='OID: 1.3.6.1.4.1.1466.115.121.1.15', max_length=200, null=True, verbose_name='schacPlaceOfBirth')),
                ('schacExpiryDate', ldap_peoples.model_fields.TimeStampField(blank=True, db_column='schacExpiryDate', help_text='Date from which the set of data is to be considered invalid', null=True)),
                ('memberOf', ldap_peoples.model_fields.MultiValueField(db_column='memberOf', editable=False)),
                ('created', ldapdb.models.fields.DateTimeField(db_column='createTimestamp', editable=False)),
                ('modified', ldapdb.models.fields.DateTimeField(db_column='modifyTimestamp', editable=False)),
                ('created_by', ldapdb.models.fields.CharField(db_column='creatorsName', editable=False, max_length=200)),
                ('modified_by', ldapdb.models.fields.CharField(db_column='modifiersName', editable=False, max_length=200)),
                ('pwdAccountLockedTime', ldapdb.models.fields.CharField(db_column='pwdAccountLockedTime', max_length=200)),
                ('pwdFailureTime', ldap_peoples.model_fields.MultiValueField(db_column='pwdFailureTime')),
                ('pwdChangedTime', ldap_peoples.model_fields.TimeStampField(db_column='pwdChangedTime')),
            ],
            options={
                'verbose_name_plural': 'LDAP Academia Users',
                'verbose_name': 'LDAP Academia User',
            },
        ),
        migrations.CreateModel(
            name='LdapGroup',
            fields=[
                # ('dn', ldapdb.models.fields.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cn', ldapdb.models.fields.CharField(db_column='cn', max_length=200, primary_key=True, serialize=False)),
                ('member', ldap_peoples.model_fields.ListField(db_column='member', default=[])),
            ],
            options={
                'verbose_name_plural': 'LDAP MemberOf Groups',
                'verbose_name': 'LDAP MemberOf Group',
            },
        ),
    ]
