# Generated by Django 2.1.3 on 2018-11-10 01:18

from django.db import migrations
import ldap_peoples.model_fields
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_peoples', '0002_auto_20181029_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldapacademiauser',
            old_name='telephone',
            new_name='telephoneNumber',
        ),
        migrations.AddField(
            model_name='ldapacademiauser',
            name='schacPersonalUniqueCode',
            field=ldap_peoples.model_fields.SchacPersonalUniqueCodeListField(blank=True, db_column='schacPersonalUniqueCode', help_text='Specifies a "unique code" for the subject it is associated with', null=True, verbose_name='schacPersonalUniqueCode'),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='eduPersonAffiliation',
            field=ldap_peoples.model_fields.eduPersonAffiliationListField(blank=True, db_column='eduPersonAffiliation', default='', help_text='Organizzazione di appartenenza e affiliazione', null=True, verbose_name='Eduperson Affiliation'),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='eduPersonPrincipalName',
            field=ldapdb.models.fields.CharField(blank=True, db_column='eduPersonPrincipalName', help_text='A scoped identifier for a person', max_length=200, null=True, verbose_name='ePPN, Eduperson PrincipalName'),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='eduPersonScopedAffiliation',
            field=ldap_peoples.model_fields.eduPersonScopedAffiliationListField(blank=True, db_column='eduPersonScopedAffiliation', default='', help_text='Organizzazione di appartenenza e affiliazione scoped.Es: affliation@istitution', null=True, verbose_name='ScopedAffiliation'),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='schacHomeOrganizationType',
            field=ldap_peoples.model_fields.SchacHomeOrganizationTypeListField(blank=True, db_column='schacHomeOrganizationType', default='', help_text='Type of a Home Organization', null=True),
        ),
    ]
