# Generated by Django 2.1.4 on 2018-12-06 11:21

from django.db import migrations
import ldap_peoples.ldap_utils
import ldap_peoples.model_fields
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_peoples', '0003_auto_20181110_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapacademiauser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ldapacademiauser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ldapacademiauser',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='ldapacademiauser',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='ldapacademiauser',
            name='createTimestamp',
            field=ldapdb.models.fields.DateTimeField(db_column='createTimestamp', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ldapacademiauser',
            name='creatorsName',
            field=ldapdb.models.fields.CharField(db_column='creatorsName', editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ldapacademiauser',
            name='modifiersName',
            field=ldapdb.models.fields.CharField(db_column='modifiersName', editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ldapacademiauser',
            name='modifyTimestamp',
            field=ldapdb.models.fields.DateTimeField(db_column='modifyTimestamp', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='eduPersonAffiliation',
            field=ldap_peoples.model_fields.eduPersonAffiliationListField(blank=True, db_column='eduPersonAffiliation', help_text='Organizzazione di appartenenza e affiliazione', null=True, verbose_name='Eduperson Affiliation'),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='eduPersonScopedAffiliation',
            field=ldap_peoples.model_fields.eduPersonScopedAffiliationListField(blank=True, db_column='eduPersonScopedAffiliation', help_text='Organizzazione di appartenenza e affiliazione scoped.Es: affliation@istitution', null=True, verbose_name='ScopedAffiliation'),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='memberOf',
            field=ldap_peoples.model_fields.MultiValueField(db_column='memberOf', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='pwdChangedTime',
            field=ldap_peoples.model_fields.TimeStampField(db_column='pwdChangedTime', editable=False),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='pwdFailureTime',
            field=ldap_peoples.model_fields.MultiValueField(db_column='pwdFailureTime', editable=False),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='schacExpiryDate',
            field=ldap_peoples.model_fields.TimeStampField(db_column='schacExpiryDate', default=ldap_peoples.ldap_utils.get_expiration_date, help_text='Date from which the set of data is to be considered invalid', null=True),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='schacHomeOrganization',
            field=ldapdb.models.fields.CharField(blank=True, db_column='schacHomeOrganization', default='testunical.it', help_text='The persons home organization using the domain of the organization.', max_length=200, null=True, verbose_name='schacHomeOrganization'),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='schacHomeOrganizationType',
            field=ldap_peoples.model_fields.SchacHomeOrganizationTypeListField(blank=True, db_column='schacHomeOrganizationType', help_text='Type of a Home Organization', null=True),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='schacPlaceOfBirth',
            field=ldapdb.models.fields.CharField(blank=True, db_column='schacPlaceOfBirth', help_text='OID: 1.3.6.1.4.1.1466.115.121.1.15', max_length=200, null=True, verbose_name='schacPlaceOfBirth'),
        ),
    ]
