# Generated by Django 2.1.4 on 2018-12-10 13:30

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_peoples', '0004_auto_20181206_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='sambaNTPassword',
            field=ldapdb.models.fields.CharField(blank=True, db_column='sambaNTPassword', editable=False, help_text='SAMBA NT Password (freeRadius PEAP)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='userPassword',
            field=ldapdb.models.fields.CharField(blank=True, db_column='userPassword', editable=False, max_length=200, null=True, verbose_name='LDAP Password'),
        ),
    ]
