# Generated by Django 2.1.4 on 2018-12-11 15:33

from django.db import migrations
import ldap_peoples.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_peoples', '0005_auto_20181210_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='eduPersonAffiliation',
            field=ldap_peoples.model_fields.eduPersonAffiliationListField(blank=True, db_column='eduPersonAffiliation', help_text='Membership and affiliation organization', null=True, verbose_name='Eduperson Affiliation'),
        ),
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='eduPersonScopedAffiliation',
            field=ldap_peoples.model_fields.eduPersonScopedAffiliationListField(blank=True, db_column='eduPersonScopedAffiliation', help_text='Membership and scopedaffiliation organization.Es: affliation@istitution', null=True, verbose_name='ScopedAffiliation'),
        ),
    ]
