# Generated by Django 2.1.4 on 2018-12-20 10:58

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_peoples', '0006_auto_20181211_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapacademiauser',
            name='cn',
            field=ldapdb.models.fields.CharField(db_column='cn', help_text='cn', max_length=200, verbose_name='Nome'),
        ),
    ]
